
name: drawloop-ws            
region: blr1                       
services:
  - name: drawloop-ws                 # a logical name for this component
    git:
      repo_clone_url: https://github.com/whosensei/Drawloop   
      branch: main
    build_command: |
      pnpm install --frozen-lockfile
      pnpm --filter ws-backend build
    run_command: pnpm --filter ws-backend start
    source_dir: apps/ws-backend      # where your package.json lives
    envs:
      - key: JWT_SECRET
        scope: RUN_AND_BUILD         # available at build & run
        value: $JWT_SECRET           # pulled from DO's env settings
      - key: DATABASE_URL
        scope: RUN_AND_BUILD
        value: $DATABASE_URL
    http_port: 8080                  # matches your WebSocketServer({port:…})
    routes:
      - path: /                      # route all traffic (incl WS upgrades) in
        preserve_path: false
